# GoReleaser configuration for Sanity CLI
# Documentation: https://goreleaser.com
version: 2

# Build configuration
# NOTE: This project uses CGO (tree-sitter C bindings). Cross-compilation is handled
# via toolchains installed in GitHub Actions (gcc-mingw-w64, gcc-aarch64-linux-gnu, OSXCross).
# For local development, use 'make build-local' to build for your platform.
builds:
  - id: sanity
    main: ./main.go
    binary: sanity
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude invalid combinations
    ignore:
      - goos: windows
        goarch: arm64
    # Inject version information
    ldflags:
      - -s -w
      - -X sanity/cmd.version={{.Version}}
      - -X sanity/cmd.buildDate={{.Date}}
      - -X sanity/cmd.commit={{.ShortCommit}}
    # Configure cross-compilation
    overrides:
      # Linux ARM64
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      # Windows AMD64
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
      # macOS AMD64 (Intel)
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      # macOS ARM64 (Apple Silicon)
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++

# Archive configuration
archives:
  - id: sanity-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# Checksums for all archives
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Generate changelog from git commits
changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - typo

# GitHub release configuration
release:
  github:
    owner: LegacyCodeHQ
    name: sanity
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"
  header: |
    ## Changelog
  footer: |
    **Full Changelog**: https://github.com/LegacyCodeHQ/sanity/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap - handled by separate workflow job
# See .github/workflows/release.yml for Homebrew tap publishing

# Snapcraft (optional - uncomment for Linux snap packages)
# snapcrafts:
#   - name: sanity
#     summary: Analyze and visualize dependency graphs
#     description: |
#       Sanity is a CLI tool for analyzing and visualizing dependency graphs
#       in your codebase, with support for Dart and Go files.
#     grade: stable
#     confinement: classic
#     publish: true
